on: [push]
name: Azure ARM
jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      steps:

        # Checkout code
      - uses: actions/checkout@main

        # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Deploy ARM Template
        uses: whiteducksoftware/azure-arm-action-js@v1
        with:
          resourceGroupName: test-github-rg
          templateLocation: azuredeploy.json
