on: [push]
name: Azure ARM
jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      steps:

        # Checkout code
      - uses: actions/checkout@main
      - name: DISPLAY SECRETS  
        run: echo "Adding some Markdown content" >> $secrets.AZURE_CREDENTIALS
        
        # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZ_Creds }}
      
