on:
  push:
    branches:
      - main
    paths:
      - "testGIUHUB.yml"
      - "azuredeploy.json"

name: Infrastructure

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Checkout Sourcecode
        uses: actions/checkout@master

      - name: Deploy ARM Template
        uses: whiteducksoftware/azure-arm-action-js@v1
        with:
          resourceGroupName: test-github-rg
          templateLocation: azuredeploy.json
          parameters: |
            appServicePlanName=test-github-Appservice 
            webAppName=StaticWebApp
